name: BuildAndTest

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'
      
      # 1. DerivedData 삭제 (캐싱 문제 방지를 위해 빌드 전 클린하게 시작)
      - name: Clean DerivedData
        run: rm -rf ~/Library/Developer/Xcode/DerivedData

      # 2. 빌드 스텝만 실행
      - name: Build Application
        run: |
          xcodebuild build \
            -project BestWish.xcodeproj \
            -scheme BestWish \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.0' \
            SYMROOT=${{ github.workspace }}/build # 빌드 결과물을 특정 폴더에 저장
          | xcbeautify

      # 3. 빌드된 아티팩트 저장 (선택 사항)
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BestWish-app-build
          path: ${{ github.workspace }}/build/Debug-iphonesimulator/BestWish.app # 빌드된 앱 경로
          # retention-days: 1 # 아티팩트 보존 기간 (선택 사항)

      # 4. 테스트 스텝만 실행
      - name: Run Tests
        run: |
          xcodebuild test \
            -project BestWish.xcodeproj \
            -scheme BestWish \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.0' \
            | xcbeautify
