name: BuildAndTest

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'
      
      # 1. DerivedData 삭제 (캐싱 문제 방지를 위해 빌드 전 클린하게 시작)
      - name: Clean DerivedData
        run: rm -rf ~/Library/Developer/Xcode/DerivedData

      # 2. 빌드 스텝만 실행
      - name: Build Application
        run: |
          xcodebuild build \
            -project BestWish.xcodeproj \
            -scheme BestWish \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.0' \
          | xcbeautify

      # 4. 테스트 스텝만 실행
      - name: Run Tests
        run: |
          xcodebuild test \
            -project BestWish.xcodeproj \
            -scheme BestWish \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.0' \
            | xcbeautify
