name: BuildAndTest

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Build and Run Tests
        run: |
          set -eo pipefail               # e: 오류시 즉시 중단 / o pipefail: 파이프 실패 감지
          xcodebuild clean test \
            -project BestWish.xcodeproj \
            -scheme BestWish \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.0' \
          | xcbeautify
